---
driver:
  name: vagrant
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: trusty64
      box_url: https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box
suites:
- name: default
  run_list:
      - recipe[apt-mirror]      
  attributes: 
    apt-mirror:
      base_path: "/ci/apt-mirror"