---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list: ["recipe[apt]"]
#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box

suites:
- name: default
  run_list: ["recipe[apt-mirror]","recipe[apt-mirror::nginx]"]
  attributes: {}
  data_bags_path: "data_bags"
