---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
  run_list:
  - "recipe[apt]"
- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"
- name: ubuntu-14.04
  run_list:
  - "recipe[apt]"

suites:
- name: default
  run_list:
  - recipe[apt-mirror]
  - recipe[apt-mirror::nginx]
  attributes:
    apt-mirror:
      data_bags:
      - "mirror1"
      - "mirror2"
